export const TOGGLE_SIDEBAR_REQUEST = 'TOGGLE_SIDEBAR_REQUEST';
export const TOGGLE_SIDEBAR_SUCCESS = 'TOGGLE_SIDEBAR_SUCCESS';
export const TOGGLE_SIDEBAR_FAILED = 'TOGGLE_SIDEBAR_FAILED';

export const APP_LOADING = 'APP_LOADING';
